name 'desktop'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures desktop'
long_description 'Installs/Configures desktop'
version '0.1.0'
